### ISSUE TITLE
CI build is failing 

### ISSUE THREAD

**Issue by Peter554** [EnableSoftware/Enable.Extensions.Queuing#25]
Example [here](https://ci.appveyor.com/project/EnableSoftware/enable-extensions-queuing/builds/22330602). Seems to be something to do with the azure authentication:

```
Microsoft.WindowsAzure.Storage.StorageException : Server failed to authenticate the request. 
Make sure the value of Authorization header is formed correctly including the signature.
```

**Comment by cgwrench** [comment]
This issue is occurring because we don't make environment variables, like the Azure Storage account connection string, available to builds triggered via pull requests (so that we don't leak any secrets). We should update the CI build configuration to not build pull requests, or perhaps to only build pull requests that are not from forked repositories.

**Comment by Peter554** [comment]
Stale - closing
